using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeekzKai.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Tables already exist, just add missing ones
            
            // Check if Messages table exists, if not create it
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Messages') THEN
                        CREATE TABLE ""Messages"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""SenderId"" integer NOT NULL,
                            ""ReceiverId"" integer NOT NULL,
                            ""Content"" text NOT NULL,
                            ""IsRead"" boolean NOT NULL,
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            CONSTRAINT ""PK_Messages"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_Messages_Users_ReceiverId"" FOREIGN KEY (""ReceiverId"") REFERENCES ""Users"" (""User_Id"") ON DELETE RESTRICT,
                            CONSTRAINT ""FK_Messages_Users_SenderId"" FOREIGN KEY (""SenderId"") REFERENCES ""Users"" (""User_Id"") ON DELETE RESTRICT
                        );
                        CREATE INDEX ""IX_Messages_ReceiverId"" ON ""Messages"" (""ReceiverId"");
                        CREATE INDEX ""IX_Messages_SenderId"" ON ""Messages"" (""SenderId"");
                    END IF;
                END $$;
            ");
            
            // Check if Follows table exists, if not create it
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'Follows') THEN
                        CREATE TABLE ""Follows"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""FollowerId"" integer NOT NULL,
                            ""FollowingId"" integer NOT NULL,
                            ""CreatedAt"" timestamp with time zone NOT NULL,
                            CONSTRAINT ""PK_Follows"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""FK_Follows_Users_FollowerId"" FOREIGN KEY (""FollowerId"") REFERENCES ""Users"" (""User_Id"") ON DELETE RESTRICT,
                            CONSTRAINT ""FK_Follows_Users_FollowingId"" FOREIGN KEY (""FollowingId"") REFERENCES ""Users"" (""User_Id"") ON DELETE RESTRICT
                        );
                        CREATE UNIQUE INDEX ""IX_Follows_FollowerId_FollowingId"" ON ""Follows"" (""FollowerId"", ""FollowingId"");
                        CREATE INDEX ""IX_Follows_FollowingId"" ON ""Follows"" (""FollowingId"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Messages");

            migrationBuilder.DropTable(
                name: "Follows");
        }
    }
}